baseURL:  /
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Ansel documentation

markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

languages:
  en:
    title: Ansel user manual
    languageName: English
    weight: 1
  fr:
    title: Ansel user manual
    contentDir: _gen/fr/content
    languageName: Français
    weight: 2
  de:
    title: Ansel user manual
    contentDir: _gen/de/content
    languageName: German
    weight: 4
  eo:
    title: Ansel user manual
    contentDir: _gen/eo/content
    languageName: Esperanto
    weight: 5
  es:
    title: Ansel user manual
    contentDir: _gen/es/content
    languageName: Español
    weight: 6
  gl:
    title: Ansel user manual
    contentDir: _gen/gl/content
    languageName: Galician
    weight: 7
  it:
    title: Ansel user manual
    contentDir: _gen/it/content
    languageName: Italian
    weight: 8
  pl:
    title: Ansel user manual
    contentDir: _gen/pl/content
    languageName: Polish
    weight: 9
  pt_br:
    title: manual do usuário Ansel
    contentDir: _gen/pt_br/content
    languageName: Português
    weight: 10
  uk:
    title: Ansel user manual
    contentDir: _gen/uk/content
    languageName: Ukrainian
    weight: 11
  nl:
    title: Ansel user manual
    contentDir: _gen/nl/content
    languageName: Dutch
    weight: 12
  ja:
    title: Ansel user manual
    contentDir: _gen/ja/content
    languageName: Japanese
    weight: 13

outputs:
  home:
    - HTML
    - RSS
    - JSON

theme:
  - github.com/aurelienpierreeng/ansel-website/themes/ansel

ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
