baseURL:  /
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Ansel documentation

markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

module:
  imports:
  - disable: false
    ignoreConfig: false
    ignoreImports: false
    path: github.com/aurelienpierreeng/ansel-website/themes/ansel
  mounts:
  - disableWatch: false
    excludeFiles: null
    includeFiles: null
    lang: ""
    source: content
    target: content/doc

languages:
  en:
    title: Ansel user manual
    languageName: English
    weight: 1
  fr:
    title: Ansel user manual
    languageName: Français
    weight: 2
  de:
    title: Ansel user manual
    languageName: German
    weight: 4
  eo:
    title: Ansel user manual
    languageName: Esperanto
    weight: 5
  es:
    title: Ansel user manual
    languageName: Español
    weight: 6
  it:
    title: Ansel user manual
    languageName: Italian
    weight: 8
  pl:
    title: Ansel user manual
    languageName: Polish
    weight: 9
  pt_br:
    title: manual do usuário Ansel
    languageName: Português
    weight: 10
  uk:
    title: Ansel user manual
    languageName: Ukrainian
    weight: 11
  nl:
    title: Ansel user manual
    languageName: Dutch
    weight: 12

outputs:
  home:
    - HTML
    - RSS
    - JSON

theme:
  - github.com/aurelienpierreeng/ansel-website/themes/ansel

ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$

ignoreLogs:
- warning-goldmark-raw-html
