baseURL:  https://ansel.photos/en/doc
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Ansel documentation

markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON


module:
  ignoreImports: true
  ignoreConfig: true
  imports:
    - path: github.com/aurelienpierreeng/ansel-website/themes/ansel


ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
