baseURL:  https://ansel.photos/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Ansel documentation

markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON

theme:
  - github.com/aurelienpierreeng/ansel-website/themes/ansel

ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
