name: Pull Request tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull-request-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run 'echo "Installed nix dependencies"'

      - name: Install assets
        run: nix-shell --run 'cd themes/hugo-Ansel-docs-theme/assets/ && yarn install'

      - name: Run linkchecker
        run: nix-shell --run 'hugo server --disableFastRender -verbose --config config.yaml -b https://Ansel-org.github.io/dtdocs/ & sleep 30 && linkchecker --ignore-url .*pdf$ --ignore-url .*epub$ --no-status http://localhost:1313/dtdocs/index.html && pkill hugo'

      - name: Generate translated files
        run: nix-shell --run 'cd tools && bash generate-translations.sh --no-update'

      - name: Clear
        run: nix-shell --run 'rm -rf public'

      - name: Build
        run: nix-shell --run 'hugo'
